baseURL = "https://docs.toot.app"
languageCode = "en-us"
defaultContentLanguage = "ja"
title = "Mastodon documentation"
pygmentsCodeFences = true
pygmentsStyle = "dracula"
metaDataFormat = "yaml"
paginate = 100
enableGitInfo = true

[menu]
  [[menu.docs]]
    name = "Using Mastodon"
    weight = 10
    identifier = "user"
    url = "/user/"
  [[menu.docs]]
    name = "Running Mastodon"
    weight = 20
    identifier = "admin"
    url = "/admin/"
  [[menu.docs]]
    name = "Developing Mastodon apps"
    weight = 30
    identifier = "client"
    url = "/client/"
  [[menu.docs]]
    name = "Contributing to Mastodon"
    weight = 40
    identifier = "dev"
    url = "/dev/"
  [[menu.docs]]
    name = "Spec compliance"
    weight = 50
    identifier = "spec"
    url = "/spec/"
  [[menu.docs]]
    name = "REST API"
    weight = 60
    identifier = "api"
    url = "/api/"
  [[menu.docs]]
    name = "API Methods"
    weight = 70
    identifier = "methods"
    url = "/methods/"
  [[menu.docs]]
    name = "API Entities"
    weight = 80
    identifier = "entities"
    url = "/entities/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = -99
  [languages.ja]
    contentDir = "content/ja"
    languageName = "日本語"
    weight = -99
    [languages.ja.menu]
	[[languages.ja.menu.docs]]
	   name = "ユーザーガイド"
	   weight = 1
    	   identifier = "usage"
           url = "/usage/"
	[[languages.ja.menu.docs]]
	   name = "管理者ガイド"
	   weight = 2
	   identifier = "administration"
	   url = "/administration/"
	[[languages.ja.menu.docs]]
	   name = "開発者ガイド"
	   weight = 3
	   identifier = "development"
	   url = "/development/"
	[[languages.ja.menu.docs]]
	   name = "APIガイド"
	   weight = 4
	   identifier = "api"
	   url = "/api/"
	[[languages.ja.menu.docs]]
	   name = "REST API一覧"
	   weight = 5
	   identifier = "rest-api"
	   url = "/api/rest/"