baseURL = "https://docs.toot.app"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Mastodon documentation"
pygmentsCodeFences = true
pygmentsStyle = "dracula"
metaDataFormat = "yaml"
paginate = 100
enableGitInfo = true

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.ja]
    contentDir = "content/ja"
    languageName = "日本語"
    weight = 1
    [languages.ja.menu]
	[[languages.ja.menu.docs]]
	   name = "ユーザーガイド"
	   weight = 1
    	   identifier = "usage"
           url = "/usage/"
	[[languages.ja.menu.docs]]
	   name = "管理者ガイド"
	   weight = 2
	   identifier = "administration"
	   url = "/administration/"
	[[languages.ja.menu.docs]]
	   name = "開発ガイド"
	   weight = 3
	   identifier = "development"
	   url = "/development/"
	[[languages.ja.menu.docs]]
	   name = "APIガイド"
	   weight = 4
	   identifier = "api"
	   url = "/api/"
	[[languages.ja.menu.docs]]
	   name = "REST API一覧"
	   weight = 5
	   identifier = "rest-api"
	   url = "/api/rest/"

[menu]
  [[menu.docs]]
    name = "User guide"
    weight = 1
    identifier = "usage"
    url = "/usage/"
  [[menu.docs]]
    name = "Administrator guide"
    weight = 2
    identifier = "administration"
    url = "/administration/"
  [[menu.docs]]
    name = "API Overview"
    weight = 4
    identifier = "api"
    url = "/api/"
  [[menu.docs]]
    name = "REST API"
    weight = 5
    identifier = "rest-api"
    url = "/api/rest/"
  [[menu.docs]]
    name = "Development guide"
    weight = 3
    identifier = "development"
    url = "/development/"