baseURL = "https://nostalgic-liskov-d0a3a9.netlify.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Mastodon documentation"
pygmentsCodeFences = true
pygmentsStyle = "dracula"
metaDataFormat = "yaml"
paginate = 100
enableGitInfo = true

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.pl]
    contentDir = "content/pl"
    languageName = "Polski"
    weight = 1
  [languages.fr]
    contentDir = "content/fr"
    languageName = "Français"
    weight = 1
    [languages.fr.menu]
	[[languages.fr.menu.docs]]
	   name = "Guide d'utilisation"
	   weight = 1
    	   identifier = "usage"
           url = "/usage/"
	[[languages.fr.menu.docs]]
	   name = "Guide d'administration"
	   weight = 2
	   identifier = "administration"
	   url = "/administration/"
	[[languages.fr.menu.docs]]
	   name = "Guide de développement"
	   weight = 3
	   identifier = "development"
	   url = "/development/"
	[[languages.fr.menu.docs]]
	   name = "Aperçu de l'API"
	   weight = 4
	   identifier = "api"
	   url = "/api/"
	[[languages.fr.menu.docs]]
	   name = "API REST"
	   weight = 5
	   identifier = "rest-api"
	   url = "/api/rest/"

[menu]
  [[menu.docs]]
    name = "User guide"
    weight = 1
    identifier = "usage"
    url = "/usage/"
  [[menu.docs]]
    name = "Administrator guide"
    weight = 2
    identifier = "administration"
    url = "/administration/"
  [[menu.docs]]
    name = "API Overview"
    weight = 4
    identifier = "api"
    url = "/api/"
  [[menu.docs]]
    name = "REST API"
    weight = 5
    identifier = "rest-api"
    url = "/api/rest/"
  [[menu.docs]]
    name = "Development guide"
    weight = 3
    identifier = "development"
    url = "/development/"